apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-petclinic
  namespace: argocd
operation:
  initiatedBy:
    automated: true
  retry:
    limit: 5
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: demo1
  source:
    path: chart
    repoURL: https://github.com/roie710/spring-petclinic.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
